language: cpp

complier:
  - gcc

install:
  - sudo apt-get install cmake python-pip python-dev
  - pip install --upgrade pip
  - pip install cget

build:
  - echo "Hello world"
  - cd Minimac4
  - bash install.sh
