dist: xenial
language: cpp

complier:
  - gcc

#env:
#  - LD_LIBRARY_PATH=/usr/local/lib

install:
  - sudo apt-get install cmake python-pip python-dev bzip2 libboost-all-dev libopenblas-dev time
  - sudo pip install --upgrade pip
  - pip install --user cget
  - wget https://github.com/samtools/htslib/releases/download/1.9/htslib-1.9.tar.bz2
  - tar xvjf htslib-1.9.tar.bz2
  - pushd htslib-1.9 && ./configure --prefix=/usr && make && sudo make install && popd
  - bash install.sh
  - wget https://github.com/daheise/Eagle/archive/parallel-bgz.zip
  - unzip parallel-bgz.zip
  - pushd Eagle-parallel-bgz/src && make && popd
  - pushd Eagle-parallel-bgz && ln -s src/eagle eagle && popd
  - pushd Eagle-parallel-bgz/tables
  - rm *.gz
  - wget  https://data.broadinstitute.org/alkesgroup/Eagle/downloads/tables/genetic_map_hg19_withX.txt.gz
  - popd
  - wget ftp://share.sph.umich.edu/minimac3/G1K_P3_M3VCF_FILES_WITH_ESTIMATES.tar.gz
  - tar -xvzf G1K_P3_M3VCF_FILES_WITH_ESTIMATES.tar.gz 21.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz
  - rm G1K_P3_M3VCF_FILES_WITH_ESTIMATES.tar.gz

script:
  - release-build/minimac4 --noPhoneHome --help || if [ $? -eq 255 ]; then echo "Expected non-zero exit code"; fi
  - pushd Eagle-parallel-bgz/example && bash run_example_vcf.sh && popd
  - /usr/bin/time -v release-build/minimac4 --noPhoneHome --refHaps ./21.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz --haps ./Eagle-parallel-bgz/example/phased.vcf.gz --minRatio 0.01  --prefix test-all --cpus 2 --vcfBuffer 200 --format GT,DS,HDS,GP
  - /usr/bin/time -v release-build/minimac4 --noPhoneHome --refHaps ./21.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz --haps ./Eagle-parallel-bgz/example/phased.vcf.gz --minRatio 0.01  --prefix test-ds --cpus 2 --vcfBuffer 200 --format DS    
  - /usr/bin/time -v release-build/minimac4 --noPhoneHome --refHaps ./21.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz --haps ./Eagle-parallel-bgz/example/phased.vcf.gz --minRatio 0.01  --prefix test-gp --cpus 2 --vcfBuffer 200 --format GP
  - /usr/bin/time -v release-build/minimac4 --noPhoneHome --refHaps ./21.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz --haps ./Eagle-parallel-bgz/example/phased.vcf.gz --minRatio 0.01  --prefix test-gt --cpus 2 --vcfBuffer 200 --format GT
  - /usr/bin/time -v release-build/minimac4 --noPhoneHome --refHaps ./21.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz --haps ./Eagle-parallel-bgz/example/phased.vcf.gz --minRatio 0.01  --prefix test-hds --cpus 2 --vcfBuffer 200 --format HDS
  - /usr/bin/time -v release-build/minimac4 --noPhoneHome --refHaps ./21.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz --haps ./Eagle-parallel-bgz/example/phased.vcf.gz --minRatio 0.01  --prefix test-sav --cpus 2 --vcfBuffer 200 --sav
  - /usr/bin/time -v cget/bin/sav export -d DS  -f vcf test.dose.sav | bgzip -@2 -c > test-ds.dose.vcf.bgz
  - /usr/bin/time -v cget/bin/sav export -d GP  -f vcf test.dose.sav | bgzip -@2 -c > test-gp.dose.vcf.bgz
  - /usr/bin/time -v cget/bin/sav export -d GT  -f vcf test.dose.sav | bgzip -@2 -c > test-gt.dose.vcf.bgz
  - /usr/bin/time -v cget/bin/sav export -d HDS -f vcf test.dose.sav | bgzip -@2 -c > test-hds.dose.vcf.bgz
  - ls -lh *.dose*
